// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  MemSentry CLI — Compiler Driver (implementation)                           ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

#include "compiler_driver.hpp"

#include <array>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <sstream>

#ifdef _WIN32
    #include <windows.h>
#endif

namespace memsentry::cli {

namespace fs = std::filesystem;

CompilerDriver::CompilerDriver(const CliOptions& opts) : opts_(opts) {}

// ─── Find Visual Studio's vcvarsall.bat ──────────────────────────────────────
#ifdef _WIN32
static auto find_vcvarsall() -> std::string {
    // Common Visual Studio installation paths
    const char* editions[] = {"Professional", "Enterprise", "Community", "BuildTools"};
    const char* years[]    = {"2022", "2019"};

    for (const auto* year : years) {
        for (const auto* ed : editions) {
            auto path = std::string("C:\\Program Files\\Microsoft Visual Studio\\")
                + year + "\\" + ed + "\\VC\\Auxiliary\\Build\\vcvarsall.bat";
            if (fs::exists(path)) return path;

            // Also check (x86) for older installs
            auto path86 = std::string("C:\\Program Files (x86)\\Microsoft Visual Studio\\")
                + year + "\\" + ed + "\\VC\\Auxiliary\\Build\\vcvarsall.bat";
            if (fs::exists(path86)) return path86;
        }
    }
    return {};
}
#endif

// ─── Auto-detect compiler ────────────────────────────────────────────────────
auto CompilerDriver::detect_compiler() const -> Result<std::string> {
    if (!opts_.compiler_path.empty()) {
        return opts_.compiler_path;
    }

#ifdef _WIN32
    // On Windows, try to find MSVC via vcvarsall.bat
    auto vcvars = find_vcvarsall();
    if (!vcvars.empty()) {
        // Return a special marker — build_command will wrap with vcvarsall
        return std::string("msvc:" + vcvars);
    }

    // Try g++ and clang++ on PATH (MinGW, MSYS2)
    const char* candidates[] = {"g++", "clang++"};
    for (const auto* name : candidates) {
        std::string test_cmd = std::string(name) + " --version >nul 2>&1";
        if (std::system(test_cmd.c_str()) == 0) {
            return std::string(name);
        }
    }
#else
    const char* candidates[] = {"g++", "clang++", "c++"};
    for (const auto* name : candidates) {
        std::string test_cmd = std::string(name) + " --version >/dev/null 2>&1";
        if (std::system(test_cmd.c_str()) == 0) {
            return std::string(name);
        }
    }
#endif

    return Result<std::string>::err(
        "No C++ compiler found. Install MSVC, GCC, or Clang, "
        "or use --compiler <path>."
    );
}

// ─── Generate the MemSentry instrumentation wrapper ─────────────────────────
// This file wraps the user's main() so MemSentry hooks are active during
// the entire program execution.
auto CompilerDriver::generate_wrapper(const fs::path& wrapper_path) const -> bool {
    std::ofstream out(wrapper_path);
    if (!out) return false;

    // Determine config preset
    std::string config_call = (opts_.analysis_mode == AnalysisMode::Minimal)
        ? "memsentry::Config::minimal()"
        : "memsentry::Config::full_analysis()";

    // Determine report format
    std::string format_line;
    switch (opts_.output_format) {
        case OutputFormat::JSON: format_line = "cfg.report_format = memsentry::ReportFormat::JSON;"; break;
        case OutputFormat::HTML: format_line = "cfg.report_format = memsentry::ReportFormat::HTML;"; break;
        default:                 format_line = "cfg.report_format = memsentry::ReportFormat::Text;"; break;
    }

    // Output file
    std::string output_line;
    if (!opts_.output_file.empty()) {
        // Escape backslashes for C++ string
        std::string escaped_path = opts_.output_file;
        for (std::size_t pos = 0; (pos = escaped_path.find('\\', pos)) != std::string::npos; pos += 2) {
            escaped_path.insert(pos, "\\");
        }
        output_line = "cfg.report_output_path = \"" + escaped_path + "\";";
    }

    // The report will be written to a temp file so the CLI can read it
    // after the binary exits. This avoids all piping/redirect issues.
    auto report_file = (fs::temp_directory_path() / "memsentry_build" / "_memsentry_report.txt").string();
    for (auto& c : report_file) { if (c == '\\') c = '/'; }

    out << R"cpp(// ── MemSentry Auto-Generated Wrapper ──────────────────────────────────────
// This file is generated by the MemSentry CLI tool. It wraps the user's
// program with MemSentry instrumentation so all heap operations are tracked.

#include <memsentry/memsentry.hpp>
#include <iostream>
#include <fstream>
#include <sstream>

// Forward-declare the user's main as user_main
// (we rename it via preprocessor below)
#define main user_main
)cpp";

    // Include all user source files
    for (const auto& src : opts_.source_files) {
        auto abs_path = fs::absolute(src).string();
        // Normalize path separators for C++ include
        for (auto& c : abs_path) {
            if (c == '\\') c = '/';
        }
        out << "#include \"" << abs_path << "\"\n";
    }

    out << R"cpp(
#undef main

// ── Instrumented main ────────────────────────────────────────────────────────
int main() {
    // Configure MemSentry — conservative settings for CLI analysis.
    auto cfg = )cpp" << config_call << R"cpp(;
    cfg.scanner_interval_ms = 0;  // no background thread
    cfg.max_stack_depth = 0;      // disable stack capture entirely
    cfg.redzone_size = 0;         // disable redzones (avoids CRT heap conflicts)
    cfg.enable_overflow_detection = false;
    cfg.enable_uninit_detection = false;
    cfg.enable_cycle_detection = false;
    cfg.enable_fragmentation_analysis = false;
    )cpp" << format_line << R"cpp(
)cpp";

    if (!output_line.empty()) {
        out << "    " << output_line << "\n";
    }

    out << R"cpp(
    // Initialize MemSentry (hooks enabled, no background scanner)
    memsentry::MemSentry::init(cfg);

    // Add a file sink so the CLI can read the report after we exit
    memsentry::MemSentry::report_engine().add_output_sink([](const std::string& s) {
        std::ofstream rf(")cpp" << report_file << R"cpp(");
        if (rf) rf << s;
    });

    int exit_code = 0;
    {
        // Run the user's program within the MemSentry scope
        try {
            exit_code = user_main();
        } catch (const std::exception& ex) {
            std::cerr << "\n[MemSentry] Caught unhandled exception: " << ex.what() << "\n";
            exit_code = 1;
        } catch (...) {
            std::cerr << "\n[MemSentry] Caught unknown exception\n";
            exit_code = 1;
        }
    }

    // Disable hooks before generating report (avoids recursive tracking)
    memsentry::disable_hooks();

    // Generate and output the report (goes to stderr + temp file)
    auto report = memsentry::MemSentry::report();
    memsentry::MemSentry::report_engine().output(report);
    memsentry::MemSentry::shutdown();

    return exit_code;
}
)cpp";

    return out.good();
}

// ─── Build the full compiler command ────────────────────────────────────────
auto CompilerDriver::build_command(const std::string& compiler,
                                    const fs::path& wrapper,
                                    const fs::path& output) const -> std::string
{
    std::ostringstream cmd;

    bool is_msvc = compiler.starts_with("msvc:") ||
                    (compiler.find("cl") != std::string::npos &&
                     compiler.find("clang") == std::string::npos);

    if (is_msvc) {
        // ── MSVC (cl.exe via vcvarsall) ────────────────────────────────────
        // We invoke cl.exe through vcvarsall.bat to set up the environment
        if (compiler.starts_with("msvc:")) {
            auto vcvars_path = compiler.substr(5);  // strip "msvc:" prefix
            cmd << "\"" << vcvars_path << "\" x64 && cl.exe";
        } else {
            cmd << "\"" << compiler << "\"";
        }
        cmd << " /EHsc /std:" << opts_.cpp_standard;
        cmd << " /DMEMSENTRY_PLATFORM_WINDOWS=1";
        cmd << " /DMEMSENTRY_HAS_SOURCE_LOCATION=1";
        cmd << " /DMEMSENTRY_HAS_FORMAT=1";
        cmd << " /DMEMSENTRY_HAS_JTHREAD=1";
        cmd << " /D_CRT_SECURE_NO_WARNINGS";
        cmd << " /W4 /permissive- /Zc:__cplusplus /GS-";

        // MemSentry include path
        auto memsentry_include = get_memsentry_include_dir();
        cmd << " /I\"" << memsentry_include.string() << "\"";

        // User extra include dirs
        for (const auto& inc : opts_.include_dirs) {
            cmd << " /I\"" << fs::absolute(inc).string() << "\"";
        }

        // Source files
        cmd << " \"" << wrapper.string() << "\"";

        // MemSentry library source files
        for (const auto& src : get_memsentry_sources()) {
            cmd << " \"" << src.string() << "\"";
        }

        // Put .obj files in the temp build directory so the linker finds them,
        // and name the output .exe explicitly using /Fe with the temp path
        // (this avoids issues when CWD has stale/missing .obj files).
        auto obj_dir = fs::temp_directory_path() / "memsentry_build";
        cmd << " /Fo\"" << obj_dir.string() << "\\\\\"";
        cmd << " /Fe\"" << output.string() << "\"";

        // Link libraries
        cmd << " /link dbghelp.lib";
    } else {
        // ── GCC / Clang ──────────────────────────────────────────────────────
        cmd << compiler;
        cmd << " -std=" << opts_.cpp_standard;
        cmd << " -DMEMSENTRY_PLATFORM_LINUX=1";
        cmd << " -DMEMSENTRY_HAS_SOURCE_LOCATION=1";
        cmd << " -DMEMSENTRY_HAS_FORMAT=1";
        cmd << " -DMEMSENTRY_HAS_JTHREAD=1";
        cmd << " -Wall -Wextra";

        auto memsentry_include = get_memsentry_include_dir();
        cmd << " -I\"" << memsentry_include.string() << "\"";

        for (const auto& inc : opts_.include_dirs) {
            cmd << " -I\"" << fs::absolute(inc).string() << "\"";
        }

        cmd << " \"" << wrapper.string() << "\"";

        for (const auto& src : get_memsentry_sources()) {
            cmd << " \"" << src.string() << "\"";
        }

        cmd << " -lpthread -ldl";
        cmd << " -o \"" << output.string() << "\"";
    }

    return cmd.str();
}

// ─── Execute a shell command and capture output ─────────────────────────────
auto CompilerDriver::exec_command(const std::string& cmd) -> ExecResult {
    std::string output;

    // On Windows, cmd /c needs the entire command wrapped in an outer set of quotes
    // when the command itself contains quoted paths with spaces
#ifdef _WIN32
    std::string full_cmd = "cmd /c \"" + cmd + " 2>&1\"";
#else
    std::string full_cmd = cmd + " 2>&1";
#endif

#ifdef _WIN32
    FILE* pipe = _popen(full_cmd.c_str(), "r");
#else
    FILE* pipe = popen(full_cmd.c_str(), "r");
#endif

    if (!pipe) {
        return {-1, "Failed to execute command"};
    }

    std::array<char, 4096> buffer;
    while (std::fgets(buffer.data(), static_cast<int>(buffer.size()), pipe)) {
        output += buffer.data();
    }

#ifdef _WIN32
    int code = _pclose(pipe);
#else
    int code = pclose(pipe);
#endif

    return {code, output};
}

// ─── Main compile entry point ───────────────────────────────────────────────
auto CompilerDriver::compile() -> Result<fs::path> {
    // 1. Detect compiler
    auto compiler = detect_compiler();
    if (!compiler) return Result<fs::path>::err(compiler.error());

    if (opts_.verbose) {
        std::cout << "[MemSentry] Using compiler: " << *compiler << "\n";
    }

    // 2. Create temp directory for build artifacts
    auto temp_dir = fs::temp_directory_path() / "memsentry_build";
    fs::create_directories(temp_dir);

    // 3. Generate the instrumentation wrapper
    auto wrapper_path = temp_dir / "_memsentry_wrapper.cpp";
    if (!generate_wrapper(wrapper_path)) {
        return Result<fs::path>::err("Failed to generate instrumentation wrapper at: " +
                               wrapper_path.string());
    }

    if (opts_.verbose) {
        std::cout << "[MemSentry] Generated wrapper: " << wrapper_path << "\n";
    }

    // 4. Determine output binary name — use temp dir to keep CWD clean
#ifdef _WIN32
    auto output_path = temp_dir / "memsentry_target.exe";
#else
    auto output_path = temp_dir / "memsentry_target";
#endif

    // 5. Build the compile command
    auto cmd = build_command(*compiler, wrapper_path, output_path);

    if (opts_.verbose) {
        std::cout << "[MemSentry] Compile command:\n    " << cmd << "\n";
    }

    // 6. Execute compilation
    auto result = exec_command(cmd);

    if (result.exit_code != 0) {
        return Result<fs::path>::err(
            "Compilation failed (exit code " + std::to_string(result.exit_code) + "):\n" +
            result.output
        );
    }

    if (opts_.verbose && !result.output.empty()) {
        std::cout << "[MemSentry] Compiler output:\n" << result.output << "\n";
    }

    return output_path;
}

// ─── Helper: get MemSentry include directory ─────────────────────────────────
// The include/ directory is located relative to the memsentry executable.
// Layout: <install>/bin/memsentry.exe  →  <install>/include/
auto get_memsentry_include_dir() -> fs::path {
    // Try relative to current working directory first
    if (fs::exists("include/memsentry/memsentry.hpp")) {
        return fs::absolute("include");
    }

    // Try relative to executable
#ifdef _WIN32
    char buf[MAX_PATH];
    GetModuleFileNameA(nullptr, buf, MAX_PATH);
    auto exe_dir = fs::path(buf).parent_path();
#else
    auto exe_dir = fs::read_symlink("/proc/self/exe").parent_path();
#endif

    // Check <exe_dir>/../include/
    auto include_dir = exe_dir.parent_path() / "include";
    if (fs::exists(include_dir / "memsentry" / "memsentry.hpp")) {
        return include_dir;
    }

    // Fall back to current directory
    return fs::current_path() / "include";
}

// ─── Helper: get all MemSentry .cpp source files ─────────────────────────────
// These are the core library sources that get compiled alongside user code.
auto get_memsentry_sources() -> std::vector<fs::path> {
    std::vector<fs::path> sources;

    // Try relative to working directory
    fs::path src_dir = "src";
    if (!fs::exists(src_dir)) {
#ifdef _WIN32
        char buf[MAX_PATH];
        GetModuleFileNameA(nullptr, buf, MAX_PATH);
        src_dir = fs::path(buf).parent_path().parent_path() / "src";
#else
        src_dir = fs::read_symlink("/proc/self/exe").parent_path().parent_path() / "src";
#endif
    }

    // Collect all .cpp files from MemSentry source dirs (not cli/)
    const char* subdirs[] = {"core", "detectors", "capture", "reporting", "threading", "platform"};
    for (const auto* sub : subdirs) {
        auto dir = src_dir / sub;
        if (!fs::exists(dir)) continue;
        for (const auto& entry : fs::directory_iterator(dir)) {
            if (entry.is_regular_file() && entry.path().extension() == ".cpp") {
                sources.push_back(fs::absolute(entry.path()));
            }
        }
    }

    return sources;
}

} // namespace memsentry::cli
